"""empty message

Revision ID: 6ea17a552696
Revises: 2c5acc2f1f54
Create Date: 2020-03-13 00:04:02.211293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea17a552696'
down_revision = '2c5acc2f1f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profiles', sa.Column('date_joined', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Profiles', 'date_joined')
    # ### end Alembic commands ###
